# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Tale
paginate:       5
baseurl:        ""
url:            "https://github.com/SonGuku/theme"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Wen Zixun
  url:          http://www.wenzixunblog.com
  email:        524172206@qq.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/SonGuku/theme

# Gems
gems:
  - jekyll-paginate
